# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfc9dbbc1e761028186fc3712151a9cd4e69e18efb4cfdb100cac22fe1275aa7866d1b8b849b4ff5acc4fe6f7b79767dbd0e1e2c840100162dfcfdd55d95445a

test:
  secret_key_base: 0391758230380368e697ff7b9b728e0981151e366c6c57fbec3a9944088324f10ed3d54ca8178c9bb20f8250c35947ec9ba1f64a4b4af5012ed7a62b285932a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
